os:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
customCommands:
  - key: "o"
    command: "nvim -c ':Octo pr create'"
    context: "localBranches"
    loadingText: "Loading Octo"
    description: "Open pull request with Octo"
    subprocess: true
keybinding:
  branches:
    createPullRequest: "O"
